### ISSUE TITLE
NPM package isn't updated

### ISSUE THREAD

**Issue by kaioduarte** [kmwhelan93/react-geocoder-autocomplete#3]
Hi @kmwhelan93, I'm trying to use your package, but it still using old dependencies.

![image](https://user-images.githubusercontent.com/11046907/50171206-f9e16300-02d8-11e9-9513-8dbadbb526c7.png)

**Comment by kaioduarte** [comment]
A workaround that I found: add the dependencie with git link such as
`"react-geocoder-autocomplete": "github:kmwhelan93/react-geocoder-autocomplete"`

**Comment by kmwhelan93** [comment]
Hey @kaioduarte are you referring to react `15.x` dependencies? Those were updated to react 16 recently in https://github.com/kmwhelan93/react-geocoder-autocomplete/pull/2. I'm sorry that I do not maintain this repo. If you'd like to change something, I encourage you to try making the change yourself.

**Comment by kaioduarte** [comment]
@kmwhelan93 yes, just the NPM package that seems outdated, downloading from git works fine.

**Comment by kmwhelan93** [comment]
Oh I see. Never got published because I never set up any build system. I just published `3.1.0`. You should be able to depend on that now.

**Comment by kaioduarte** [comment]
Thanks!
